plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - LICENSE.md
baseurl: /depsek

title: Thingking Machine
description: A machine is a thing. Things can not think. ...but some of them can thingk!
